### ISSUE TITLE
add SEO friendly name for your image

### ISSUE THREAD

**Issue by ghost** [ngant-ictu/Front-End-Engineers-Test#1]
currently your image name is `1.jpeg`. That is not good for SEO and it makes it harder to organize/maintain files. Please give your image a SEO friendly name and be sure to also include the SEO friendly text in your `alt` tag.

**Comment by grace-nguyen** [comment]
I changed.
![img](https://user-images.githubusercontent.com/13827300/39280768-5eb5ccf2-492b-11e8-8edd-493619acecbd.png)

**Comment by ghost** [comment]
@ngant-ictu thank you resovling
