### ISSUE TITLE
Mixing pascal case with hyphenated-lowercase

### ISSUE THREAD

**Issue by ghost** [ngant-ictu/Front-End-Engineers-Test#5]
https://github.com/ngant-ictu/Front-End-Engineers-Test/blob/fafb21cf274890813708649bdce28ac0bab598c7/Step1/index.html#L47

I see you mixing the use of `pascalCase` selectors with `hyphenated-lowercase` selectors. 
please choose a class naming convention and follow it

**Comment by ghost** [comment]
I also saw this:

`<div class="hits_and_comments">`

please use a standard rule for class naming

**Comment by grace-nguyen** [comment]
I fixed.

**Comment by grace-nguyen** [comment]
I changed class in html to `hyphenated-lowercase`
![changehtml](https://user-images.githubusercontent.com/13827300/39280671-e299e694-492a-11e8-9845-80966d0f62ca.png)

**Comment by ghost** [comment]
@ngant-ictu good choice :) thank you
