### ISSUE TITLE
split up your sass into manageable files

### ISSUE THREAD

**Issue by ghost** [ngant-ictu/Front-End-Engineers-Test#6]
Most of your sass is written in one file, `Step1/scss/template.scss`.

It would be better to divide this file into more manageable sub files.

for example:

```
_base.scss
_mixins.scss
_typography.scss
components/list-item.scss
```

Also the code in the responsive folder seems like it would be hard to maintain. You should remove those files and put the media queries where they are applied in the code. For reference please look at how foundation 6 developers recommend using media queries https://foundation.zurb.com/sites/docs/media-queries.html#the-breakpoint-mixin

please refactor your code accordingly.

**Comment by grace-nguyen** [comment]
Hi Elliott.
Do you want me reference https://foundation.zurb.com/sites/docs/media-queries.html#the-breakpoint-mixin to use breakpoint-mixin and will write code directly in main file scss to stead of for responsive file?

**Comment by ghost** [comment]
@ngant-ictu 

I mean that media queries should be used exactly where they are needed (it is easier to maintain) for example, like you did here:

```
.container {
  width: 1170px;
  margin: 0 auto;

  @include breakpoint(large) {
    width: 930px;
  }

  @include breakpoint(medium) {
    width: 750px;
  }

  @include breakpoint(small) {
    width: 100%;
  }
}
```

**Comment by grace-nguyen** [comment]
I had divided file.
![splitfile](https://user-images.githubusercontent.com/13827300/39280626-a71ed188-492a-11e8-89b4-f851acf9aab3.png)
