### ISSUE TITLE
device width meta tag

### ISSUE THREAD

**Issue by ghost** [ngant-ictu/Front-End-Engineers-Test#7]
https://github.com/ngant-ictu/Front-End-Engineers-Test/blob/fafb21cf274890813708649bdce28ac0bab598c7/Step1/index.html#L7

This doesn't look like it is the most modern way to use the device width tag. It also lacks markup for how to handle IE/Edge browsers. Please research the modern markup for this meta property and update accordingly

**Comment by grace-nguyen** [comment]
I fixed.
![meta](https://user-images.githubusercontent.com/13827300/39280589-682d6728-492a-11e8-9241-fc97dc4869ea.png)

**Comment by ghost** [comment]
@ngant-ictu I see, you fixed with this commit https://github.com/ngant-ictu/Front-End-Engineers-Test/commit/f8124bc4468cd400044112808d7de144577af213

**Comment by ghost** [comment]
For future reference, if you keep a clean commit history then it is easy to connect issues to commits or branches (https://github.com/ngant-ictu/Front-End-Engineers-Test/commit/f8124bc4468cd400044112808d7de144577af213) 

closing for now
