### ISSUE TITLE
HTML tag is missing language declaration

### ISSUE THREAD

**Issue by ghost** [ngant-ictu/Front-End-Engineers-Test#8]
https://github.com/ngant-ictu/Front-End-Engineers-Test/blob/fafb21cf274890813708649bdce28ac0bab598c7/Step1/index.html#L3

Without this information, your HTML will be considered invalid by HTML validators.
Please validate your html using the w3c validation tool https://validator.w3.org/
and fix any issues

**Comment by ghost** [comment]
@ngant-ictu Please tag the commit for where you fixed each issue so I can review

**Comment by grace-nguyen** [comment]
I fixed.
![html](https://user-images.githubusercontent.com/13827300/39280564-4412c9d2-492a-11e8-8c14-2e82f7f1680e.png)

**Comment by grace-nguyen** [comment]
I had add comment for each issue.
Please check them help me.
Thank you.

Best Regards,

2018-04-26 7:52 GMT+07:00 Elliott <notifications@github.com>:

**Comment by ghost** [comment]
@ngant-ictu I prefer to have the commit where the issue was fixed, but the screenshot is helpful
